### PR TITLE
Frist implementation of Transmission Spectrum Computation

### PR DESCRIPTION
**Pull request by HajimeKawahara**
This is a first attempt to compute a transmission spectrum of CO #356 , and a comparison with @ykawashima data.

Can you confirm the results of the following code?

exojax/tests/integration/comparison/transmission/comparison_with_kawashima_transmission.py

I believe the difference between two is due to the lack of Rayleigh scattering, which I plan to implement next. Thanks in advance.

comparison_with_kawashima_transmission

### CODE REVIEW

**Comment by astrostevanus** [comment]
Thanks for the PR. I have tried the example script that you provided (comparison_with_kawashima_transmission.py) and it works without any problem. Then, I tried to compare with petitRadTrans output (pure CO, no neither rayleigh scattering nor CIA, same parameters as in Exojax's script) although using a different line list (all isotope, HITEMP instead of HITRAN). Overall, the transit radius seems to agree, but the big difference is in the longer wavelength, I am not sure if it is due to different line wing cut-off limit that was used or other possible causes.

comparison_general

**Comment by HajimeKawahara** [comment]
thanks! Do you know which broadening parameters petitRadtrans uses for HITEMP?
Both Kawashima-san and I are using the self-broadening because it's 100% CO.

**Comment by astrostevanus** [comment]
No worries! Unfortunately, they do not include that information in the website. I found in the paper that they include pressure broadening by either using the air broadening coefficients of HITRAN/HITEMP (Rothman et al.2010, 2013), or Eq. (15) of Sharp & Burrows (2007).

**Review by ykawashima — APPROVED** [review]
Thank you very much for the implementation! I have confirmed that the code works without any problem in my environment, too.

**Review by astrostevanus — APPROVED** [review]

**Comment by HajimeKawahara** [comment]
The bug fix #414 improved the agreement with Kawashima-san's results.
Figure_1

**Pull request merged**
