### PR TITLE
New spin rotation and ip sampling (only Gaussian yet)

### PR DESCRIPTION
**Pull request by HajimeKawahara**
Response to #292.
I made a non-OLA version and o cuDNN of rigid rotation convolution and IP (Gaussian) sampling. 

In this algorithm, we need top make "vr_array" to preallocate to compute rotational kernel:
```python
   #settings before HMC                                                                   
   vsini_max = 100.0
   vr_array = velocity_grid(res, vsini_max)
```
then, in HMC you can run

```python
    F0=rtrun(dtau,sourcef)
    Frot = convolve_rigid_rotation(F0, vr_array, vsini, u1, u2)
    mu=response.ipgauss_sampling(nusd,nus,Frot,beta_inst,RV)
```

### CODE REVIEW

**Comment by ykawashima** [comment]
Thank you very much! I have confirmed that the code works.

**Review by ykawashima — APPROVED** [review]

**Comment by ykawashima** [comment]
While this is not related to the commits made in this pull request, there seems to be a failure in the unit test due to the lack of src/exojax/special/_special.py.

**Comment by chonma0ctopus** [comment]
Thank you very much for the PR. 
There is a minor error due to a redundant comma:

````
============================================ ERRORS ============================================
___________ ERROR collecting tests/integration/comparison/premodit/comp_lsd_test.py ____________
../../../miniconda3/lib/python3.9/site-packages/_pytest/python.py:578: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
../../../miniconda3/lib/python3.9/site-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
../../../miniconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
../../../miniconda3/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:161: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
../../../miniconda3/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:354: in _rewrite_test
    tree = ast.parse(source, filename=fn_)
../../../miniconda3/lib/python3.9/ast.py:50: in parse
    return compile(source, filename, mode, flags,
E     File "/home/tako/ghR/exojax/tests/integration/comparison/premodit/comp_lsd_test.py", line 36
E       from exojax.spec.premodit import make_elower_grid, 
E                                                          ^
E   SyntaxError: trailing comma not allowed without surrounding parentheses
````

**Comment by chonma0ctopus** [comment]
In addition, in my environment, `pytools` was not installed until just now... 
```
ModuleNotFoundError: No module named 'pytools'
```
Do you want to add it to INSTALL_REQUIRES in setup.py?

**Pull request merged**
