### PR TITLE
uncertainties for hitran and hitemp

### PR DESCRIPTION
**Pull request by YuiKasagi**
I added functions to get the uncertainty codes of HITRAN or HITEMP database. 
The uncertainty range corresponding to the code can be found here; https://hitran.org/docs/uncertainties/

### CODE REVIEW

**Comment by YuiKasagi** [comment]
We can export the uncertainty indices by setting `with_error=True`. Here is an example of usage: 
```Python
mdb = MdbHitemp('./database/CH4/',nu_grid,with_error=True)  #mdb.ierr become available

#wavmask (optional)
wavmask = (mdb.nu_lines >= nu_grid[0]) * (mdb.nu_lines <= nu_grid[-1])
mdb.apply_mask_mdb(wavmask)

#add error
mdb.add_error()

nu_lines_err = mdb.nu_lines_err  #uncertainty indices corresponding to mdb.nu_lines
```

**Comment by HajimeKawahara** [comment]
@YuiKasagi Can you pull the current develop branch into the branch?

```sh
git pull origin develop
```

Because `hitemp_uncertainty` does not include the recent update of `develop` (in particular #394 #395), the integration tests fails.
You may test integration (need a bit time ) by
```sh
cd exojax/test/integration
pytest
```

**Comment by YuiKasagi** [comment]
I have missed to pull the current branch. Thank you for pointing it out.

I also tried `$pytest exojax/test/integration/` and it successfully passed.

**Comment by HajimeKawahara** [comment]
@YuiKasagi I couldn't pass the test for `test_hitran_with_error` (from clean download).
What's wrong?

```
Traceback (most recent call last):
  File "/home/kawahara/exojax/tests/integration/api/api_hitran_hitemp_test.py", line 55, in <module>
    test_Hitran_with_error()
  File "/home/kawahara/exojax/tests/integration/api/api_hitran_hitemp_test.py", line 46, in test_Hitran_with_error
    mdb = api.MdbHitran("CO",nus, with_error=True)
  File "/home/kawahara/exojax/src/exojax/spec/api.py", line 876, in __init__
    self.activate(df)
  File "/home/kawahara/exojax/src/exojax/spec/api.py", line 413, in activate
    self.instances_from_dataframes(df[mask])
  File "/home/kawahara/exojax/src/exojax/spec/api.py", line 906, in instances_from_dataframes
    self.ierr = df_load_mask.ierr.values.to_numpy()
  File "/home/kawahara/anaconda3/lib/python3.10/site-packages/vaex/dataframe.py", line 288, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrameLocal' object has no attribute 'ierr'
```

**Comment by HajimeKawahara** [comment]
Thanks! @YuiKasagi Can you make a new issue about the uncomment after the future merge and release of [radis PR 574](https://github.com/radis/radis/pull/574)?

**Review by HajimeKawahara — APPROVED** [review]
Thanks! All the integration and unit tests in my environment passed.

**Pull request merged**
