### PR TITLE
Improve minorthings

### PR DESCRIPTION
**Pull request by ykawashima**
Following the conversation #221, I have made several modifications;

1. As for [ipgauss_sampling](https://github.com/HajimeKawahara/exojax/blob/2e41f0e3be7155bcb66f82b8c0455270a7f12e0f/src/exojax/spec/response.py#L92), I added a warning when some sampling wavenumber points are outside the calculation wavenumber range.
2. Changed the default value of crit from -np.inf to be 0 so that the lines with zero strength will not be calculated.
3. Added a feature to remove unnecessary hdf5 and yaml files to save the user's disk space, which can be switched off by setting remove_original_hdf=False like `mdbCO=moldb.MdbExomol(emf,nus,remove_original_hdf=False)`
4. Download trans.bz2 file only when the important hdf5 file does not exist. So the user can remove the trans.bz2 file once the hdf5 file is created in case he/she wants to save the disk space.

Thank you in advance.

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
@ykawashima Thank you! 
During the unit tests, I found an error as the following. Can you try this one in your environment?
```sh
shirochan:~/exojax/tests(improve_minorthings)>python auto/autort_test.py
xsmode assumes ESLOG: mode= MODIT
nu grid is evenly spaced in log space (ESLOG).
xsmode= MODIT
H2-H2
Warning: CO is interpreted as 12C-16O
Recommendated database by ExoMol:  Li2015
CO/12C-16O/Li2015
broadf= True
Background atmosphere:  H2
Note: Couldn't find the hdf5 format. We convert data to the hdf5 format. After the second time, it will become much faster.
Reading transition file
Note: Couldn't find the hdf5 format. We convert data to the hdf5 format. After the second time, it will become much faster.
.broad is used.
Broadening code level= a0
default broadening parameters are used for  71  J lower states in  152  states
# of lines 924
xsmode= MODIT
Warning: negative cross section detected #= 942523  fraction= 0.23563075
nu grid is evenly spaced in log space (ESLOG).
xsmode= LPF
H2-H2
Warning: CO is interpreted as 12C-16O
Recommendated database by ExoMol:  Li2015
CO/12C-16O/Li2015
broadf= True
Background atmosphere:  H2
Reading transition file
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 273, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
Traceback (most recent call last):
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 273, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 273, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
Traceback (most recent call last):
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 273, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
Traceback (most recent call last):
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 273, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
Traceback (most recent call last):
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 273, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 273, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 273, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
Traceback (most recent call last):
KeyError: "Unknown variables or column: 'inf'"
```
(omitted)

**Comment by ykawashima** [comment]
Thank you for your quick check. I tried and could reproduce the error. I found this comes from the fact that crit is defined as -np.inf [here](https://github.com/ykawashima/exojax/blob/2972c620d23a7cb1b971352297d686edc20fb2ce/src/exojax/spec/autospec.py#L322), which I did not expect for the value of crit. As I imagine that many unit test files adopt -np.inf value for crit, I think it is better to allow np.inf value for crit. Is that ok for you?

**Comment by HajimeKawahara** [comment]
I see. Thanks. Yes, it is with me. But, just to use zero as the default value in autospec.py is easier? @ykawashima it's up to you.

**Comment by ykawashima** [comment]
That's true. Also, it is probably better to test with the default value. I have changed the value in autospec.py.

**Comment by HajimeKawahara** [comment]
Thank you! I confirmed the unit tests, auto/autort_test.py,  passed.

**Comment by HajimeKawahara** [comment]
I found 

```
print()
```
in ipgauss sampling made an error when performing optimization as:

```python
gd = jaxopt.GradientDescent(fun=objective, maxiter=1000,stepsize=1.e-4)
res = gd.run(init_params=initpar)
params, state = res
``` 
yielding 
```python
ConcretizationTypeError                   Traceback (most recent call last)
/tmp/ipykernel_8039/3828928227.py in <module>
      1 gd = jaxopt.GradientDescent(fun=objective, maxiter=1000,stepsize=1.e-5)
----> 2 res = gd.run(init_params=initpar)
      3 params, state = res

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/base.py in run(self, init_params, *args, **kwargs)
    213       run = decorator(run)
    214 
--> 215     return run(init_params, *args, **kwargs)
    216 
    217 

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/implicit_diff.py in wrapped_solver_fun(*args, **kwargs)
    249     args, kwargs = _signature_bind(solver_fun_signature, *args, **kwargs)
    250     keys, vals = list(kwargs.keys()), list(kwargs.values())
--> 251     return make_custom_vjp_solver_fun(solver_fun, keys)(*args, *vals)
    252 
    253   return wrapped_solver_fun

    [... skipping hidden 5 frame]

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/implicit_diff.py in solver_fun_flat(*flat_args)
    205     def solver_fun_flat(*flat_args):
    206       args, kwargs = _extract_kwargs(kwarg_keys, flat_args)
--> 207       return solver_fun(*args, **kwargs)
    208 
    209     def solver_fun_fwd(*flat_args):

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/base.py in _run(self, init_params, *args, **kwargs)
    180     jit, unroll = self._get_loop_options()
    181 
--> 182     many_step = loop.while_loop(
    183         cond_fun=self._cond_fun, body_fun=self._body_fun,
    184         init_val=init_val, maxiter=self.maxiter - 1, jit=jit,

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/loop.py in while_loop(cond_fun, body_fun, init_val, maxiter, unroll, jit)
     80     fun = jax.jit(fun, static_argnums=(0, 1, 3))
     81 
---> 82   return fun(cond_fun, body_fun, init_val, maxiter)

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/loop.py in _while_loop_lax(cond_fun, body_fun, init_val, maxiter)
     58     return it+1, val
     59 
---> 60   return jax.lax.while_loop(_cond_fun, _body_fun, (0, init_val))[1]
     61 
     62 

    [... skipping hidden 13 frame]

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/loop.py in _body_fun(_val)
     55   def _body_fun(_val):
     56     it, val = _val
---> 57     val = body_fun(val)
     58     return it+1, val
     59 

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/base.py in _body_fun(self, inputs)
    143   def _body_fun(self, inputs):
    144     (params, state), (args, kwargs) = inputs
--> 145     return self.update(params, state, *args, **kwargs), (args, kwargs)
    146 
    147   # TODO(frostig,mblondel): temporary workaround to accommodate line

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/gradient_descent.py in update(self, params, state, *args, **kwargs)
     79       (params, state)
     80     """
---> 81     return super().update(params, state, None, *args, **kwargs)
     82 
     83   def optimality_fun(self, params, *args, **kwargs):

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/proximal_gradient.py in update(self, params, state, hyperparams_prox, *args, **kwargs)
    263     """
    264     f = self._update_accel if self.acceleration else self._update
--> 265     return f(params, state, hyperparams_prox, args, kwargs)
    266 
    267   def _fixed_point_fun(self, sol, hyperparams_prox, args, kwargs):

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/proximal_gradient.py in _update_accel(self, x, state, hyperparams_prox, args, kwargs)
    232     t = state.t
    233     stepsize = state.stepsize
--> 234     y_fun_val, y_fun_grad = self._value_and_grad_fun(y, *args, **kwargs)
    235     next_x, next_stepsize = self._iter(iter_num, y, y_fun_val, y_fun_grad,
    236                                        stepsize, hyperparams_prox, args, kwargs)

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/proximal_gradient.py in _value_and_grad_fun(self, params, *args, **kwargs)
    275 
    276   def _value_and_grad_fun(self, params, *args, **kwargs):
--> 277     (value, aux), grad = self._value_and_grad_with_aux(params, *args, **kwargs)
    278     return value, grad
    279 

    [... skipping hidden 8 frame]

~/anaconda3/lib/python3.8/site-packages/jaxopt/_src/proximal_gradient.py in <lambda>(*a, **kw)
    291     else:
    292       self._fun = self.fun
--> 293       fun_with_aux = lambda *a, **kw: (self.fun(*a, **kw), None)
    294 
    295     self._value_and_grad_with_aux = jax.value_and_grad(fun_with_aux,

/tmp/ipykernel_8039/3393464750.py in objective(params)
      1 def objective(params):
----> 2     f=nflux-model_c(params,boost,nusd)
      3     g=jnp.dot(f,f)
      4     return g

/tmp/ipykernel_8039/3773571264.py in model_c(params, boost, nu1)
     35         return mu
     36 
---> 37     model=obyo(nu1,nus,numatrix_CO,mdbCO,cdbH2H2)
     38     return model

/tmp/ipykernel_8039/3773571264.py in obyo(nusd, nus, numatrix_CO, mdbCO, cdbH2H2)
     32         Frot=response.rigidrot(nus,F0,vsini,u1,u2)
     33         #Frot=rigidrotx(nus,F0,vsini,u1,u2)
---> 34         mu=response.ipgauss_sampling(nusd,nus,Frot,beta,RV)
     35         return mu
     36 

~/anaconda3/lib/python3.8/site-packages/exojax-1.1.1-py3.8.egg/exojax/spec/response.py in ipgauss_sampling(nusd, nus, F0, beta, RV)
    102         response-applied spectrum (F)
    103     """
--> 104     if(np.min(nusd) < np.min(nus) or np.max(nusd) > np.max(nus)):
    105         print('WARNING: The wavenumber range of the observational grid [', np.min(nusd), '-', np.max(nusd), ' cm^(-1)] is not fully covered by that of the model grid [', np.min(nus), '-', np.max(nus), ' cm^(-1)]. This can result in the incorrect response-applied spectrum. Check the wavenumber grids for the model and observation.', sep='')
    106 
```

**Comment by HajimeKawahara** [comment]
This is the problem when doing JIT. Sorry I did not notice that. @ykawashima 
I will make a hot fix.

**Pull request merged**
