### PR TITLE
Faetures/fftmemory

### PR DESCRIPTION
**Pull request by HajimeKawahara**
This PR improves the use of GPU memory in DIT, the detail explanation is given [here](https://github.com/HajimeKawahara/exojax/issues/88#issuecomment-877074353) / #88

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
I found a small bug... Please wait a moment for review.

**Comment by HajimeKawahara** [comment]
The negative value issue have been solved. 
See [here](https://github.com/HajimeKawahara/exojax/issues/88#issuecomment-877679196) and [here](https://github.com/HajimeKawahara/exojax/issues/88#issuecomment-877741553). 

 Sorry to keep @ykawashima waiting. it's now ready for review.

**Comment by HajimeKawahara** [comment]
tutorial for DIT added, available at [here](http://secondearths.sakura.ne.jp/exojax/develop/index.html).

**Review by ykawashima — APPROVED** [review]
Sorry for my late review. I have finished checking. Thank you.

**Pull request merged**
