### PR TITLE
VALD_WL_air

### PR DESCRIPTION
**Pull request by chonma0ctopus**
I made VALD linelists with WL_air acceptable.

(Additionally, the format of atomic data was fixed.)

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
Thanks. Does this correction include the air-vacuum conversion?

**Comment by chonma0ctopus** [comment]
Yes. You can now the VALD line data written with wavelength in air. @HajimeKawahara

**Comment by HajimeKawahara** [comment]
@chonma0ctopus I mean, in the current implementation, the line center is not converted to the vacuum value?

**Comment by chonma0ctopus** [comment]
In the current implementation, only the VALD data with vacuum wavelengths are supported.

**Comment by HajimeKawahara** [comment]
I see. Thanks!

**Review by HajimeKawahara — APPROVED** [review]

**Pull request merged**
