### PR TITLE
Refac/hitemp

### PR DESCRIPTION
**Pull request by HajimeKawahara**
Reducing DRAM for HITEMP

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
To reduce the DRAM for HITEMP, I implemented "extract" option in MdbHit. @ykawashima Can you check this new feature? 
A simple test is tests/mdbhit_extract.py

**Comment by erwanp** [comment]
For HITEMP we should compare this approach with `Radis.io.hitemp.fetch_hitemp`. It is Vaex-based and can load the full CO2 database in a few seconds.

**Comment by HajimeKawahara** [comment]
@erwanp definitely your code is faster than this implementation. We should discuss this in a common framework of I/O!

**Review by ykawashima — APPROVED** [review]
I have confirmed the code works, and the implementation has improved the read time significantly. Thank you.

**Comment by HajimeKawahara** [comment]
Thank you!

**Pull request merged**
