### PR TITLE
Nonair CO broadening using the fitting formula

### PR DESCRIPTION
**Pull request by HajimeKawahara**
_Note: this capability is tentatively in ExoJAX. We should move this to radis.api in future if it's useful._

I made the computation of CO nonair broadening using the fitting formula by HITRAN2020 paper and [planetary-broadeners](https://github.com/hitranonline/planetary-broadeners).

The following examples assume hydrogen background atmosphere.  

## Comparison (HITRAN/CO/nonair vs radis)
code: exojax/tests/integration/comparison/nonair/nonair_co_hitran_comp.py
comp_nonair_1
comp_nonair_2

## Application to HITEMP
code: exojax/tests/integration/moldb/nonair_co_hitemp.py

I am not sure if we can apply the formula to HITEMP. But, anyway computed.
comph2_1
comph2_2

Comment welcome.

### CODE REVIEW

**Comment by KoHosokawa** [comment]
Thank you for updating those! I succeeded to run the test files without any problems.

**Review by KoHosokawa — APPROVED** [review]

**Comment by HajimeKawahara** [comment]
See [here](http://secondearths.sakura.ne.jp/exojax/develop/userguide/nonair.html) as a doc.

**Review by ykawashima — APPROVED** [review]
I am sorry for my late response. Thank you very much! I have confirmed that the code works.

**Comment by erwanp** [comment]
@minouHub btw, you might be interested

**Pull request merged**
