### PR TITLE
Release v1.5

### PR DESCRIPTION
**Pull request by HajimeKawahara**
## release process v1.5

- The document is [here](https://secondearths.sakura.ne.jp/exojax/develop/).
- See [here](https://github.com/HajimeKawahara/exojax/milestone/8) for the new capabilities and changes of v1.5.

We plan to release v1.5 by the end of April 2024. 

Any comments welcome!

### CODE REVIEW

**Review by ykawashima — APPROVED** [review]
Thank you very much!
I have confirmed that the files in tests/manual_check work with #483 except for the following scripts, which seem to be outdated;
- [autort.py](https://github.com/HajimeKawahara/exojax/blob/releasev1.5/tests/manual_check/auto/autort.py)
- [autoxs.py](https://github.com/HajimeKawahara/exojax/blob/releasev1.5/tests/manual_check/auto/autoxs.py)
- [errCO_REDIT.py](https://github.com/HajimeKawahara/exojax/blob/releasev1.5/tests/manual_check/comparison/hi_dynamic_range/errCO_REDIT.py)

**Review by kemasuda — APPROVED** [review]

**Comment by astrostevanus** [comment]
Thank you for the pull request. I can confirm that most of the scrips in the manual_check work well. I found that these scripts in the manual_check folder are also outdated. They still refer to the AutoXS and AutoRT:
1. [readme_sample.py](https://github.com/HajimeKawahara/exojax/blob/releasev1.5/tests/manual_check/readme_sample.py)
2. [comparison/modit_comparison.py](https://github.com/HajimeKawahara/exojax/blob/releasev1.5/tests/manual_check/comparison/modit_comparison.py)

**Comment by HajimeKawahara** [comment]
Install problem about `radis`

**Comment by HajimeKawahara** [comment]
It will be solved after the merge of https://github.com/radis/radis/pull/651 into `radis/develop`.

**Review by sh-tada — APPROVED** [review]

**Review by YuiKasagi — APPROVED** [review]

**Review by astrostevanus — APPROVED** [review]

**Review by KoHosokawa — APPROVED** [review]

**Comment by HajimeKawahara** [comment]
Thank all of the reviewers so much!

**Pull request merged**
