### PR TITLE
reduced 6 Qt functions to 3

### PR DESCRIPTION
**Pull request by HajimeKawahara**
I refactored partition functions in MdbHit. #270 

### MdbHit
- `QT_iso_interp(idx, T)`:  interpolated value of Q(isotope, T) -> `QT_interp`
- `qr_iso_interp(idx, T)`:  interpolated value of of q(isotope, T) = Q(isotope, T)/Q(isotope, Tref) -> `qr_interp`
- `Qr_HAPI(Tarr)`: Qr = partition function ratio array [N_Tarr x N_iso], N_Tarr = len(Tarr), N_iso = len(self.uniqiso), using `QT_iso_interp`, **=> ditch**
- `Qr_line_HAPI(T)`: Qr (actually, qr because T-array has 1 element T) for all of the line using `Qr_HAPI`  **=> ditch**
- `Qr_line_HAPI_jax(T)`: `Qr_line_HAPI(T)` for JAX using `qr_iso_interp(idx, T)` => `qr_interp_line`
- `Qr_layer_HAPI(Tarr)`:  Qr for layers and lines using `Qr_HAPI(Tarr)` [N_Tarr x Nlines] **=> ditch**

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
Also, I removed Qt functions using Exomol.

**Comment by chonma0ctopus** [comment]
> Also, I removed Qt functions using Exomol.

You may want to add this WARNING to the following two files.
the warning "`warnings.warn("Not working using the current version. You need to modify ExomolQT.",UserWarning)`" as well as examples/LUH16A/advanced/MassHITbug/fit.py .

examples/tutorial/Comparing HITEMP and ExoMol.ipynb
documents/tutorials/comparison_db.rst

**Comment by HajimeKawahara** [comment]
Thanks! revised.

**Review by chonma0ctopus — APPROVED** [review]
Looks good. Thank you for the refactoring.

**Pull request merged**
