### PR TITLE
Release v1_6

### PR DESCRIPTION
**Pull request by HajimeKawahara**
Release Version 1.6 
See https://github.com/HajimeKawahara/exojax/milestone/12

I would merge the PR to `master` probably the end of September after the release of `radis 0.15.2` (https://github.com/radis/radis/milestone/24) .

### CODE REVIEW

**Review by KoHosokawa — APPROVED** [review]
Thank you for the Updates! I confirmed those don't cause any problems in my environment.

**Review by ykawashima — APPROVED** [review]
Thank you very much for the updates. I tried the scripts under ``tests/manual_check`` and realized that the following codes are outdated due to the removal of auto_xsection.
- tests/manual_check/comparison/dit_hitran_CO.py
- tests/manual_check/comparison/modit_hitran_CO.py
- tests/manual_check/comparison/hi_dynamic_range/errCO_DIT.py
- tests/manual_check/comparison/hi_dynamic_range/errCO_MODIT.py
- tests/manual_check/xs/Ttyp_demo.py

**Review by YuiKasagi — APPROVED** [review]

**Comment by HajimeKawahara** [comment]
Current code coverage:

```sh
pytest --cov=src/exojax --cov-report=term-missing tests/unittests
```

```sh
---------- coverage: platform linux, python 3.10.9-final-0 -----------
Name                                             Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------
src/exojax/__init__.py                               7      0   100%
src/exojax/atm/__init__.py                           7      0   100%
src/exojax/atm/amclouds.py                          37     12    68%   27, 50-51, 94-95, 110-112, 151-153, 206
src/exojax/atm/atmconvert.py                        13     13     0%   3-57
src/exojax/atm/atmphys.py                           63     63     0%   4-180
src/exojax/atm/atmprof.py                           64     13    80%   46-47, 101, 204-206, 229-236, 251, 267
src/exojax/atm/condensate.py                        20      2    90%   85-86
src/exojax/atm/idealgas.py                           3      1    67%   17
src/exojax/atm/lorentz_lorenz.py                     4      4     0%   1-18
src/exojax/atm/mixratio.py                           4      4     0%   5-32
src/exojax/atm/polarizability.py                     2      0   100%
src/exojax/atm/psat.py                              43     23    47%   74, 106-108, 128, 143, 147-170
src/exojax/atm/simple_clouds.py                      2      2     0%   4-18
src/exojax/atm/viscosity.py                         47      7    85%   101-102, 118-122
src/exojax/atm/vterm.py                             40     16    60%   127-143
src/exojax/data/__init__.py                          7      0   100%
src/exojax/dynamics/__init__.py                      7      0   100%
src/exojax/dynamics/getE.py                         67      7    90%   146-152
src/exojax/dynamics/rvfunc.py                       52     52     0%   6-106
src/exojax/experimental/__init__.py                  7      0   100%
src/exojax/experimental/ditfnu.py                   58     58     0%   11-171
src/exojax/experimental/moditfnu.py                 49     49     0%   11-157
src/exojax/experimental/presolar.py                 28      1    96%   94
src/exojax/experimental/redit.py                    50     50     0%   2-104
src/exojax/experimental/shapefilter.py              13      3    77%   42, 52-53
src/exojax/plot/__init__.py                          8      8     0%   1-10
src/exojax/plot/atmplot.py                          96     96     0%   3-218
src/exojax/plot/ditplot.py                          34     34     0%   2-62
src/exojax/plot/opaplot.py                          31     31     0%   1-42
src/exojax/plot/rtplot.py                           31     31     0%   1-45
src/exojax/signal/__init__.py                        1      0   100%
src/exojax/signal/convolve.py                        9      0   100%
src/exojax/signal/integrate.py                       6      0   100%
src/exojax/signal/ola.py                            80      0   100%
src/exojax/spec/__init__.py                         10      0   100%
src/exojax/spec/api.py                             459    184    60%   53, 180, 201, 214, 230-233, 237, 239, 266, 292, 307-318, 439-442, 447, 449, 491, 502, 517-531, 543-544, 617, 626-634, 719, 726-770, 793, 819, 823, 829, 857, 878, 933-1011, 1022-1023, 1034-1066, 1069-1076, 1079, 1082-1113, 1123-1150, 1169
src/exojax/spec/atmrt.py                           219     76    65%   104, 123-127, 133, 177, 203-208, 225, 229, 301, 323, 340, 352, 440-442, 466-481, 511-513, 542-561, 592-594, 616-651, 727-731, 733, 756, 818-822, 846-863
src/exojax/spec/atomll.py                          198    178    10%   37-53, 115-147, 207-223, 282-334, 395-421, 481-529, 542-548, 562, 589-625, 640-646, 679-718, 733-756, 772-782, 796-800
src/exojax/spec/atomllapi.py                       156    107    31%   173-257, 280-392, 430-472, 500-503, 518-526, 583-587, 605-623
src/exojax/spec/contdb.py                           31     31     0%   5-57
src/exojax/spec/dit.py                             112    112     0%   7-292
src/exojax/spec/ditkernel.py                        43     20    53%   27-29, 52-69, 89-94
src/exojax/spec/dtau_mmwl.py                        27     16    41%   37-46, 68, 90-102
src/exojax/spec/exomol.py                           12      4    67%   22-25, 56
src/exojax/spec/generate_elower_grid_trange.py      66     66     0%   4-178
src/exojax/spec/hitran.py                           28      2    93%   110-111
src/exojax/spec/hitranapi.py                        36      6    83%   23, 27-31
src/exojax/spec/hitrancia.py                        48      0   100%
src/exojax/spec/hminus.py                           69     19    72%   156-176
src/exojax/spec/initspec.py                         88     23    74%   48-57, 168, 170, 216, 221, 242-253, 265
src/exojax/spec/layeropacity.py                     42     25    40%   59-79, 95-99, 118-133, 152-161, 190-193
src/exojax/spec/lbd.py                              52      7    87%   38, 88, 92-93, 111-114
src/exojax/spec/lbderror.py                        137     57    58%   108-123, 162-167, 184-206, 229, 237, 268, 270, 286-297, 311, 316-320, 324-327
src/exojax/spec/limb_darkening.py                    4      0   100%
src/exojax/spec/lpf.py                              71     36    49%   29-39, 59-111, 148-202, 258-264, 281-283, 317-318, 334, 350
src/exojax/spec/lsd.py                              61     13    79%   54-62, 199-202
src/exojax/spec/make_numatrix.py                    52     36    31%   22, 25, 42-44, 59-62, 79-83, 102-106, 110-129
src/exojax/spec/mie.py                              91     41    55%   44-66, 79, 140-153, 247-261, 284, 286, 326-339
src/exojax/spec/modit.py                           160     73    54%   183-185, 255-257, 288-296, 352-404, 423-476, 503-505, 584-623, 627-629, 657-698, 721-725, 740-742, 756-758, 773-777, 793-797
src/exojax/spec/modit_scanfft.py                    44      3    93%   134-137
src/exojax/spec/moldb.py                           216    216     0%   4-597
src/exojax/spec/molinfo.py                          60     13    78%   27-30, 91, 98-100, 229-234
src/exojax/spec/multimol.py                         91     74    19%   37-40, 46-69, 88-135, 146-158, 180-194, 204-212, 239-249, 261-268
src/exojax/spec/nonair.py                           12      0   100%
src/exojax/spec/opacalc.py                         330     78    76%   103, 114, 129, 156, 194-198, 215-219, 239-244, 468-488, 497-502, 566, 583, 772, 801-824, 842-955
src/exojax/spec/opachord.py                         20      0   100%
src/exojax/spec/opacitytools.py                      9      0   100%
src/exojax/spec/opacont.py                         111     44    60%   29-30, 43-47, 50, 55, 104-106, 123-124, 223-278, 296-297
src/exojax/spec/optgrid.py                          54     20    63%   38, 56-57, 101, 106-126, 130-140
src/exojax/spec/pardb.py                           108     41    62%   40, 69-106, 160, 165-168, 174, 179-180, 199, 210-218, 253-267, 284, 309-310
src/exojax/spec/planck.py                            5      0   100%
src/exojax/spec/premodit.py                        140      8    94%   227-236, 251, 359
src/exojax/spec/qstate.py                            2      0   100%
src/exojax/spec/rayleigh.py                         14      8    43%   38-41, 45-55
src/exojax/spec/response.py                         47      0   100%
src/exojax/spec/rtransfer.py                       149     79    47%   90-93, 151, 179-209, 221-224, 290-296, 314-331, 350-361, 387-395, 413-425, 441-453, 459-487, 497-498, 502-503, 507-508, 512-513, 524-525
src/exojax/spec/set_ditgrid.py                      75     22    71%   23-24, 32, 52, 61, 79-96, 146
src/exojax/spec/specop.py                           46      3    93%   44, 81, 116
src/exojax/spec/spin_rotation.py                    37      9    76%   85-101
src/exojax/spec/toon.py                             32     25    22%   22-26, 45-46, 70-72, 76-84, 88-93, 97-100
src/exojax/spec/twostream.py                        75     51    32%   30-62, 83-121, 135-145, 158, 173-178, 228
src/exojax/spec/unitconvert.py                      30      6    80%   31-33, 57-59
src/exojax/special/__init__.py                      10      0   100%
src/exojax/special/erfcx.py                         13      0   100%
src/exojax/special/expn.py                          26      0   100%
src/exojax/special/faddeeva.py                      52     12    77%   111-121, 125-126, 142-143
src/exojax/special/j0.py                            27      0   100%
src/exojax/special/lognormal.py                     16      0   100%
src/exojax/test/__init__.py                          1      0   100%
src/exojax/test/data.py                             22      0   100%
src/exojax/test/emulate_broadpar.py                 16     16     0%   4-48
src/exojax/test/emulate_mdb.py                      44      5    89%   29, 98-102
src/exojax/test/emulate_pdb.py                      10      1    90%   30
src/exojax/test/generate.py                         35     35     0%   4-62
src/exojax/test/generate_methane_spectrum.py        60     60     0%   5-105
src/exojax/test/generate_methane_trans.py           63     63     0%   5-110
src/exojax/test/generate_pdb.py                     10     10     0%   4-32
src/exojax/test/generate_rt.py                      70     70     0%   1-106
src/exojax/test/generate_xs.py                      94     94     0%   1-154
src/exojax/utils/__init__.py                         7      0   100%
src/exojax/utils/astrofunc.py                        6      0   100%
src/exojax/utils/checkarray.py                      11      0   100%
src/exojax/utils/constants.py                       28      0   100%
src/exojax/utils/files.py                            8      8     0%   1-40
src/exojax/utils/gpkernel.py                         5      5     0%   3-21
src/exojax/utils/grids.py                           84     15    82%   64-67, 73-75, 90-91, 97-102, 169-170
src/exojax/utils/indexing.py                        58      3    95%   106, 189-190
src/exojax/utils/instfunc.py                        16      3    81%   10-12
src/exojax/utils/interp.py                           6      0   100%
src/exojax/utils/isodata.py                          7      0   100%
src/exojax/utils/isotopes.py                        38      0   100%
src/exojax/utils/jaxstatus.py                       12      2    83%   18-19
src/exojax/utils/memuse.py                          63     13    79%   21, 55, 130-134, 150-158
src/exojax/utils/mollabel.py                        30     10    67%   23-24, 125-135
src/exojax/utils/molname.py                        118     13    89%   35-36, 63-64, 125, 270-278
src/exojax/utils/progbar.py                          7      0   100%
src/exojax/utils/url.py                             24     24     0%   7-89
src/exojax/utils/zsol.py                            61      0   100%
------------------------------------------------------------------------------
TOTAL                                             6127   2874    53%

==================================== 221 passed, 3797 warnings in 60.04s (0:01:00) =====================================
```

**Review by astrostevanus — APPROVED** [review]
Thanks a lot for the updates! I can confirm that this version works well on my computer. I haven't had any issues so far.

**Review by kemasuda — APPROVED** [review]
I was able to compute a transmission spectrum using this version and A100.

**Review by sh-tada — APPROVED** [review]

**Comment by HajimeKawahara** [comment]
ready for merge, after the release of `radis==v0.15.2` https://github.com/radis/radis/pull/700, I will release v1.6.

**Pull request merged**
