### PR TITLE
Reviced api.py for non-air broadening parameter

### PR DESCRIPTION
**Pull request by KoHosokawa**
Added in Mdbhitran class;
- Definition of extra-params so that one can select whether or not to include broadening parameters(e.g. h2, he...) when downloading from Hitran
- Definition of each broadening parameter when it exists in downloaded hitran database

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
Thanks! @KoHosokawa 

- Currently, extra_params is None or "all". So, False or True is adequate? Or do you plan some extension in future for instance, "all", "H2O", "CO" etc?

- I have the following error. Can you check it?

```python
>>> import numpy as np
>>> from exojax.utils.grids import wavenumber_grid
>>> from exojax.spec import api
>>> nus,wav,res=wavenumber_grid(6910,6990,100000,unit='cm-1',xsmode="premodit")
xsmode =  premodit
xsmode assumes ESLOG in wavenumber space: mode=premodit
>>> mdb = api.MdbHitran("CO",nus,extra_params="all")
Using /home/kawahara/exojax/downloads__can_be_deleted/CO


Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_1
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.data
Header written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_1.header
END DOWNLOAD
                     Lines parsed: 1344
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_2
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_2.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_2.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_2.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_2.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_2.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_2.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_2.data
Header written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_2.header
END DOWNLOAD
                     Lines parsed: 1042
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_3
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_3.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_3.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_3.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_3.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_3.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_3.data
Header written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_3.header
END DOWNLOAD
                     Lines parsed: 920
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_4
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_4.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_4.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_4.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_4.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_4.data
Header written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_4.header
END DOWNLOAD
                     Lines parsed: 800
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_5
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_5.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_5.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_5.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_5.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_5.data
Header written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_5.header
END DOWNLOAD
                     Lines parsed: 674
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_6
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_6.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_6.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_6.data
  65536 bytes written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_6.data
Header written to /home/kawahara/exojax/downloads__can_be_deleted/CO/CO_6.header
END DOWNLOAD
                     Lines parsed: 601
PROCESSED
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kawahara/exojax/src/exojax/spec/api.py", line 762, in __init__
    self.activate(df)
  File "/home/kawahara/exojax/src/exojax/spec/api.py", line 806, in activate
    self.gQT, self.T_gQT = hitranapi.make_partition_function_grid_hitran(
  File "/home/kawahara/exojax/src/exojax/spec/hitranapi.py", line 56, in make_partition_function_grid_hitran
    len_max = np.max(len_idx)
  File "<__array_function__ internals>", line 5, in amax
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2733, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/kawahara/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
>>> 
```

**Comment by HajimeKawahara** [comment]
This was the error when there is no line in the wavelength range. Thanks!

**Comment by KoHosokawa** [comment]
I'll note it about 1st question as a log, just in case
I wrote so because the radis/hitranapi/download_and_parse command which mdbhitran refers uses "extra_params" to switch whether to include the non-air broadening parameter for downloading data or not. 
I thought it would be fewer codes to add that to not change the parameter name. so we can define other parameter name and rename them.
And since the above radis script defines "all" or "none", we need to revise radis/hitranapi to define other situations or use the HAPI command directly.
Thanks for reviewing & merging it!

**Comment by ykawashima** [comment]
Thank you! I am sorry for the delay in reviewing. I have confirmed that with the current develop branch, I can get non-air broadening parameters for HITRAN/CO, CO2, and H2S.

**Pull request merged**
